name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }}  --password-stdin
      
      - name: Build and push Docker images
        run: |
          cd frontend
          docker build -t reactjs-frontend:latest .
          docker push reactjs-frontend:latest
          cd ../backend
          docker build -t express-server:latest .
          docker push express-server:latest
          cd ..
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
      
      - name: Check cluster status
        run: |
          cluster_status=$(terraform output cluster_status)
          if [ "$cluster_status" = "running" ]; then
            echo "Cluster already running, skipping deployment"
            exit 0
          fi
      
      - name: Create Kubernetes cluster
        env:
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
        run: |
          terraform init
          terraform apply -auto-approve -var "do_token=$DO_TOKEN"
     
      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml
